default:
  image: iwphp:latest

variables:
  HOSTNAME: "iwmain2.local"

syntax-check:
  stage: test
  # variables:
  #   CI_DEBUG_TRACE: "true"
  script:
#    - apk update && apk add git
    - chmod a+x ./.cicd/syntax/*.sh
    - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | ./.cicd/syntax/syntaxcheck.sh
  tags:
    - web


# job-on-mr:
#   stage: test
#   script:
#     - apk update && apk add git
#     - cd ./.cicd/unit
#     - chmod a+x *.sh
#     - git diff-tree --no-commit-id --name-only -r origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -r $CI_COMMIT_SHA | ./run-from-input.sh
#   only:
#     - merge_requests
#   tags:
#     - web

# build-job:
#   stage: build
#   script:
#     - cd ./.cicd/build
#     - chmod a+x *.sh
#     - ./run.sh
#   tags:
#     - web
  # except:
  #   - main

test-job:
  stage: test
  script:
    - cd ./.cicd/unit
    - chmod a+x *.sh
    - ./run.sh
  tags:
    - web
  # except:
  #   - main

# infrastructure-deploy:
#   stage: deploy
#   before_script:
# #    - apt -y update && apt -y install openssh-client rsync
# #    - apk update && apk add openssh-client rsync
#     - eval $(ssh-agent -s)
#     - echo "$SSH_KEY" | ssh-add -
#     - mkdir ~/.ssh
#     - curl "https://iac.local/hostkeys/${HOSTNAME}" > ~/.ssh/known_hosts
#   script:
#     - rsync -atv --delete --progress ./.cicd/infrastructure cicd@${HOSTNAME}:~/gitlabtmp
#     - ssh cicd@${HOSTNAME} 'cd ~/gitlabtmp/infrastructure && chmod a+x *.sh && ./run.sh'
#   tags:
#     - web
#   only:
#     - infrastructure-deploy

#
# deploy-prod:
#   stage: deploy
#   variables:
#     DEPLOYPATH: /var/www/prod/${CI_PROJECT_NAME}
#   before_script:
# #    - apt -y update && apt -y install openssh-client rsync
# #    - apk update && apk add openssh-client rsync
#     - eval $(ssh-agent -s)
#     - echo "$SSH_KEY" | ssh-add -
#     - mkdir ~/.ssh
#     - curl "https://iac.local/hostkeys/${HOSTNAME}" > ~/.ssh/known_hosts
#   script:
#     - ssh cicd@${HOSTNAME} "mkdir -p ${DEPLOYPATH}"
#     - rsync -atv --delete --progress ./.cicd/updatedb cicd@${HOSTNAME}:${DEPLOYPATH}/.cicd
#     - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/updatedb && chmod a+x *.sh && ./run.sh"
#   tags:
#     - web
#   only:
#     - updatedb
#

deploy-prod2:
  stage: deploy
  variables:
    DEPLOYPATH: /var/www/prod/${CI_PROJECT_NAME}
    HOSTNAME: "iwmain2.local"
  before_script:
#    - apt -y update && apt -y install openssh-client rsync
#    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -
    - mkdir ~/.ssh
    - curl "https://iac.local/hostkeys/${HOSTNAME}" > ~/.ssh/known_hosts
  script:
    - ssh cicd@${HOSTNAME} "mkdir -p ${DEPLOYPATH}"
    - rsync -atv --delete --progress ./.cicd/integration cicd@${HOSTNAME}:${DEPLOYPATH}/.cicd
    - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/integration && chmod a+x *.sh && ./run.sh ${DEPLOYPATH}"
    - rsync -atv --delete --progress ./ cicd@${HOSTNAME}:${DEPLOYPATH} --exclude '/main'
    - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/deploy && chmod a+x *.sh &&  ./run.sh ${DEPLOYPATH}"
    - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH} && chmod a+x ${DEPLOYPATH}/.cicd/nginx/nginx.sh && ${DEPLOYPATH}/.cicd/nginx/nginx.sh prod"
    - ssh cicd@${HOSTNAME} "echo -n \"<?php define('GITADMVERSION3', '${CI_COMMIT_SHA}'); ?>\" > /var/www/prod/conf/admversion3.inc.php";
  tags:
    - web
  only:
    - main

  # except:
  #   - main


deploy-beta2:
  stage: deploy
  variables:
    DEPLOYPATH: /var/www/beta/${CI_PROJECT_NAME}
    HOSTNAME: "iwmain2.local"
  before_script:
#    - apt -y update && apt -y install openssh-client rsync
#    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -
    - mkdir ~/.ssh
    - curl "https://iac.local/hostkeys/${HOSTNAME}" > ~/.ssh/known_hosts
  script:
    - ssh cicd@${HOSTNAME} "mkdir -p ${DEPLOYPATH}"
    - rsync -atv --delete --progress ./.cicd/integration cicd@${HOSTNAME}:${DEPLOYPATH}/.cicd
    - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/integration && chmod a+x *.sh && ./run.sh ${DEPLOYPATH}"
    - rsync -atv --delete --progress ./ cicd@${HOSTNAME}:${DEPLOYPATH} --exclude '/main'
    - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/deploy && chmod a+x *.sh &&  ./run.sh ${DEPLOYPATH}"
    - git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH} && chmod a+x ${DEPLOYPATH}/.cicd/nginx/nginx.sh && ${DEPLOYPATH}/.cicd/nginx/nginx.sh beta"
    - ssh cicd@${HOSTNAME} "echo -n \"<?php define('GITADMVERSION3', '${CI_COMMIT_SHA}'); ?>\" > /var/www/beta/conf/admversion3.inc.php";
  tags:
    - web
  only:
    - beta
#
#
# deploy-alfa:
#   stage: deploy
#   variables:
#     DEPLOYPATH: /var/www/alfa/${CI_PROJECT_NAME}
#   before_script:
# #    - apt -y update && apt -y install openssh-client rsync
# #    - apk update && apk add openssh-client rsync
#     - eval $(ssh-agent -s)
#     - echo "$SSH_KEY" | ssh-add -
#     - mkdir ~/.ssh
#     - curl "https://iac.local/hostkeys/${HOSTNAME}" > ~/.ssh/known_hosts
#   script:
#     - ssh cicd@${HOSTNAME} "mkdir -p ${DEPLOYPATH}"
#     - rsync -atv --delete --progress ./.cicd/integration cicd@${HOSTNAME}:${DEPLOYPATH}/.cicd
#     - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/integration && chmod a+x *.sh && ./run.sh"
#     - rsync -atv --delete --progress ./ cicd@${HOSTNAME}:${DEPLOYPATH}  --exclude '/main'
#     - ssh cicd@${HOSTNAME} "cd ${DEPLOYPATH}/.cicd/deploy && chmod a+x *.sh &&  ./run.sh ${DEPLOYPATH}"
#   tags:
#     - web
#   only:
#     - alfa
